dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    secure: RrxTTBkCHeCA7G9fS0Yta99n9IE2IIUibTQ2N6UI1wqG+eLo8w8s8O2X3BFbbCv2xF4Xi76LOxqa6NRW7POB2EjUz5zAxCkWkbtABLdxIbRooCGBJ+UWoyVjkJUJVybZKjT7J16ENNclFHWvr721Xv31Bwjwd7aCTkEhGg0fKP6lWyqmQjTDnS8NYSf0vzp/dKWT5dd+HIXXmnZ1RRrlpk9ItyU6p6DCQd67jKuxWA+8aMgF5SzVMqhhfnaKGXxCr2XD0QG8OWF3eOgbDqXWDzlx/W2GR9d+fHKVuuxpaS7t2tdV345hBpuMhn9Sj7lgh1cNewZBZsIKyOPCkWS07S0KLFtMNbb5dUJSVzXxn0+s5u6EhYmVUC/wn9Ny/Uod5hg+tyzm8UW84i4TyRD+GE8XFDBnmMhY264b62h0+jLlFs3qfqicClXEwaPSyN8+komk2cV5mr9aTb71nzbAn9t0DLn1O1tbey+Q3R1tm5EpSr5nj/ZgBVu6A4nUbOTZ2mGNSapSYqtRstBVj6vVYTv2g/FJRFML/gKpu1wEjIYRkVeu1bdh8YSUJ+gtTJPCJgt0o4Ne3QEVkPjXB0F2idz/1HoDNjpiUD71rvQjGxWiMcMk7b+G5hkUATNrSiyAYxwcxeOH1oyulBWsIMzZH3JkqlZVuPSoTsDeZO0jz/I=
